### ISSUE TITLE
mp3 file invalid

### ISSUE THREAD

**Issue by ghost** [rorpage/openfaas-text-to-speech#1]
The downloaded mp3 files wont play.
when trying to check the file on ubuntu the following is recieved:
'NoneType' object has no attribute 'group'

**Comment by burf2000** [comment]
I got the same issue to

**Comment by rorpage** [comment]
@shlomofan @burf2000  It appears this is a token issue with gTTS: https://github.com/pndurette/gTTS/issues/151

I'll keep checking on it but we might be at the mercy of gTTS-token.

**Comment by vrabbi** [comment]
The gtts-cli works on a Ubuntu VM but not via the function. It seems the issue is in the function

**Comment by rgee0** [comment]
I've raised this which should resolve: https://github.com/rorpage/openfaas-text-to-speech/pull/3
